/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket.views;

/**
 *
 * @author XPC
 */
public class InventarioMenu extends javax.swing.JFrame {

    /**
     * Creates new form InventarioMenu
     */
    public InventarioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inventario = new javax.swing.JMenu();
        nuevoProducto = new javax.swing.JMenu();
        actualizarProducto = new javax.swing.JMenu();
        eliminarProducto = new javax.swing.JMenu();
        volver = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 78, 119));
        jLabel3.setText("Área de Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
        );

        jMenuBar1.setBackground(new java.awt.Color(24, 78, 119));

        inventario.setBackground(new java.awt.Color(24, 78, 119));
        inventario.setForeground(new java.awt.Color(245, 249, 250));
        inventario.setText("Inventario");
        inventario.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(inventario);

        nuevoProducto.setBackground(new java.awt.Color(24, 78, 119));
        nuevoProducto.setForeground(new java.awt.Color(245, 249, 250));
        nuevoProducto.setText("Nuevo Producto");
        nuevoProducto.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        nuevoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(nuevoProducto);

        actualizarProducto.setBackground(new java.awt.Color(24, 78, 119));
        actualizarProducto.setForeground(new java.awt.Color(245, 249, 250));
        actualizarProducto.setText("Actualizar Producto");
        actualizarProducto.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        actualizarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(actualizarProducto);

        eliminarProducto.setBackground(new java.awt.Color(24, 78, 119));
        eliminarProducto.setForeground(new java.awt.Color(245, 249, 250));
        eliminarProducto.setText("Eliminar Producto");
        eliminarProducto.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        eliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(eliminarProducto);

        volver.setBackground(new java.awt.Color(24, 78, 119));
        volver.setForeground(new java.awt.Color(245, 249, 250));
        volver.setText("Volver");
        volver.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jMenuBar1.add(volver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseClicked

        ListarProducto listProd = new ListarProducto();
        listProd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inventarioMouseClicked

    private void nuevoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoProductoMouseClicked

        AgregarProducto addProd = new AgregarProducto();
        addProd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevoProductoMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    private void actualizarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarProductoMouseClicked
        // TODO add your handling code here:
        ModificarProducto updateProd = new ModificarProducto();
        updateProd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_actualizarProductoMouseClicked

    private void eliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarProductoMouseClicked
        // TODO add your handling code here:
        EliminarProducto removeProd = new EliminarProducto();
        removeProd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actualizarProducto;
    private javax.swing.JMenu eliminarProducto;
    private javax.swing.JMenu inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu nuevoProducto;
    private javax.swing.JMenu volver;
    // End of variables declaration//GEN-END:variables
}
