/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket.views;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import supermarket.bo.FacturaBO;
import supermarket.entity.Factura;
import supermarket.models.FacturaTableModel;

/**
 *
 * @author XPC
 */
public class ListadoFacturas extends javax.swing.JFrame {
    
    
    private FacturaBO fbo = new FacturaBO();
    List<Factura> facturasHoy = new ArrayList<>();
    List<Factura> facturasDia = new ArrayList<>();
    
    /**
     * Creates new form ListadoFacturas
     */
    public ListadoFacturas() {
        initComponents();
        facturasPorDíaHoy();
        loadFacturas(fbo.listarTodo());
    }
    
    private void loadFacturas(List<Factura> listado) {
        /*if(ventasHoy.isSelected()){
            listadoFacturas.setModel(new FacturaTableModel(facturasHoy));
            ventas.setSelected(true);
        }else{
            listadoFacturas.setModel(new FacturaTableModel(fbo.listarTodo()));
        }*/
        listadoFacturas.setModel(new FacturaTableModel(listado));
    }
    
    
    private void facturasPorDíaHoy(){
        for(Factura f: fbo.listarTodo()){
            if(f.getFecha().getDay() == new Date().getDay()){
                System.out.println("SI");
                facturasHoy.add(f);
            }
        }
    }
    
    private void facturasPorDía(int n){
        Calendar c = Calendar.getInstance();
        for(Factura f: fbo.listarTodo()){
            c.setTime(f.getFecha());
            int dia = c.get(Calendar.DAY_OF_MONTH);
            if(dia == n){
                //System.out.println("SI");
                facturasDia.add(f);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listadoFacturas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ventasHoy = new javax.swing.JRadioButton();
        ventas = new javax.swing.JRadioButton();
        dia = new javax.swing.JTextField();
        filtrarDia = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        listadoFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listadoFacturas);

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 78, 119));
        jLabel3.setText("Listado de Facturas");

        ventasHoy.setText("Ventas de hoy");
        ventasHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasHoyActionPerformed(evt);
            }
        });

        ventas.setText("Todas las ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });

        filtrarDia.setText("Filtrar por día (dd):");
        filtrarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filtrarDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(ventasHoy)
                                .addGap(66, 66, 66)
                                .addComponent(ventas)
                                .addGap(69, 69, 69))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ventasHoy)
                    .addComponent(ventas)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtrarDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void ventasHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasHoyActionPerformed
        ventas.setSelected(false);
        filtrarDia.setSelected(false);
        loadFacturas(facturasHoy);
    }//GEN-LAST:event_ventasHoyActionPerformed

    private void filtrarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDiaActionPerformed
        facturasDia = new ArrayList<>();
        ventas.setSelected(false);
        ventasHoy.setSelected(false);
        facturasPorDía(Integer.valueOf(dia.getText()));
        loadFacturas(facturasDia);
    }//GEN-LAST:event_filtrarDiaActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        filtrarDia.setSelected(false);
        ventasHoy.setSelected(false);
        loadFacturas(fbo.listarTodo());
    }//GEN-LAST:event_ventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dia;
    private javax.swing.JRadioButton filtrarDia;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listadoFacturas;
    private javax.swing.JRadioButton ventas;
    private javax.swing.JRadioButton ventasHoy;
    // End of variables declaration//GEN-END:variables
}
