DROP TABLE BitacoraTablasMaestras;
DROP TABLE BitacoraTablaCajero;
DROP TABLE BitacoraFactura;
DROP TABLE DETALLE_FACTURA;
DROP TABLE FACTURA;
DROP TABLE CAJERO;
DROP TABLE USUARIO;
DROP TABLE PRODUCTO;

CREATE TABLE PRODUCTO(
PLU INT NOT NULL,
TIPO VARCHAR(50)NOT NULL,
DESCRIPCION VARCHAR(50)NOT NULL,
PESO FLOAT NOT NULL,
PRECIO FLOAT NOT NULL,
CANTIDAD INT NOT NULL,
EAN VARCHAR(50) NOT NULL,
CONSTRAINT PK_PLU PRIMARY KEY(PLU)
);

CREATE TABLE USUARIO(
ID INT NOT NULL,
ROL INT NOT NULL,
NOMBRE VARCHAR(50),
CLAVE VARCHAR(50),
CORREO VARCHAR(50),
CONSTRAINT PK_ID PRIMARY KEY(ID)
);

CREATE TABLE CAJERO(
NUMERO_CAJA INT NOT NULL,
ID_USUARIO INT NOT NULL,
CONSTRAINT PK_NUMERO_CAJA PRIMARY KEY(NUMERO_CAJA),
CONSTRAINT FKID_USUARIO FOREIGN KEY(ID_USUARIO)REFERENCES USUARIO(ID)
);

CREATE TABLE FACTURA(
NUMERO INT NOT NULL,
SUBTOTAL FLOAT NOT NULL,
TOTAL FLOAT NOT NULL,
FECHA TIMESTAMP NOT NULL,
CANTIDAD INT NOT NULL,
ID_CAJERO INT NOT NULL,
PLU INT NOT NULL,
CONSTRAINT PK_NUMERO PRIMARY KEY(NUMERO),
CONSTRAINT FK_ID_CAJERO FOREIGN KEY(ID_CAJERO)REFERENCES CAJERO(NUMERO_CAJA),
CONSTRAINT FK_PLU FOREIGN KEY(PLU)REFERENCES PRODUCTO(PLU)
);

CREATE TABLE DETALLE_FACTURA(
    DETALLE_FACTURA INT NOT NULL,
    NUMERO INT NOT NULL,
    PLU INT NOT NULL, 
    CANTIDAD INT NOT NULL,
    PRECIO_PRODUCTOS FLOAT NOT NULL,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (DETALLE_FACTURA), 
    CONSTRAINT FK_FACTURA FOREIGN KEY (NUMERO) REFERENCES FACTURA (NUMERO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (PLU) REFERENCES PRODUCTO (PLU)
);

CREATE TABLE BitacoraTablasMaestras(
OPERACION VARCHAR(30),
USUARIO VARCHAR(30),
FECHA DATE,
HORA VARCHAR2(5),
TABLA VARCHAR(30)
);

CREATE TABLE BitacoraTablaCajero(
USUARIO INT,
NUMERO_CAJA INT,
FECHA_VENTA DATE,
HORA_VENTA VARCHAR(2)
);

CREATE TABLE BitacoraFactura(
ARTICULO VARCHAR(30),
CANTIDAD INT,
SUBTOTAL FLOAT,
TOTAL FLOAT,
ID_CAJERO INT,
FECHA DATE,
HORA VARCHAR2(5)
);

/*
Insert into USUARIO (ID,ROL,NOMBRE,CLAVE,CORREO) values (402,1,'Diego Quiros','1234','diego@gmail.com');
Insert into USUARIO (ID,ROL,NOMBRE,CLAVE,CORREO) values (150,2,'Kevin Brenes','4321','kevin@gmail.com');
Insert into USUARIO (ID,ROL,NOMBRE,CLAVE,CORREO) values (370,1,'Jairo Ulloa','1234','jairo@gmail.com');
*/

select * from producto;

select * from usuario;




